import Head from "next/head";
import { useTranslations } from "next-intl";
import { GetStaticPropsContext } from "next";
import { LocaleSwitcher } from "@/components/localeSwitcher";
import { LocaleSwitcherFlags } from "@/components/localeSwitcherFlags";

export default function Home() {
  const t = useTranslations("Index");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={``}>
        <h1>{t("title")}</h1>
        <p>{t("description")}</p>
        <p>without flags</p>
        <LocaleSwitcher />
        <hr />
        <p>With flags</p>
        <LocaleSwitcherFlags />
      </main>
    </>
  );
}

export async function getStaticProps({ locale }: GetStaticPropsContext) {
  return {
    props: {
      messages: (await import(`@/locales/${locale}.json`)).default,
    },
  };
}
